# Generated by Django 2.1.7 on 2019-08-05 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        ('Remittance', '0001_initial'),
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remittance',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_remittance', to='market.Product'),
        ),
        migrations.AddField(
            model_name='remittance',
            name='remittance_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remittance_customer', to='UserProfile.CustomUser', verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='remittance',
            name='remittance_seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remittance_seller', to='UserProfile.CustomUser', verbose_name='Продавець'),
        ),
        migrations.AddField(
            model_name='changesawaitingconfirmation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.CustomUser'),
        ),
        migrations.AddField(
            model_name='changesawaitingconfirmation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_changes', to='market.Product'),
        ),
        migrations.AddField(
            model_name='changesawaitingconfirmation',
            name='remittance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='Remittance.Remittance'),
        ),
    ]
