# Generated by Django 2.1.7 on 2019-08-07 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Remittance', '0002_auto_20190805_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changesawaitingconfirmation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_changes', to='market.Product'),
        ),
    ]
