# Generated by Django 2.1.7 on 2019-08-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='count_of_paid_parts',
        ),
        migrations.AddField(
            model_name='product',
            name='payment_by_installments',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
