# Generated by Django 2.1.7 on 2019-08-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('photo_message', models.ImageField(blank=True, upload_to='message_image/')),
                ('record_voice', models.FileField(blank=True, upload_to='message_voice/')),
                ('read_status', models.BooleanField(blank=True, null=True)),
                ('date_created', models.DateTimeField()),
            ],
        ),
    ]
