# Generated by Django 2.1.7 on 2019-08-05 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Chat', '0001_initial'),
        ('Remittance', '0001_initial'),
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagechat',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.CustomUser'),
        ),
        migrations.AddField(
            model_name='messagechat',
            name='remittance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Remittance.Remittance'),
        ),
    ]
