# Generated by Django 2.1.7 on 2019-08-05 11:15

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Chat', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('Remittance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('custom_email', models.EmailField(blank=True, error_messages={'unique': 'Пользователь с таким email уже существует'}, max_length=254, unique=True, verbose_name='email')),
                ('user_image', models.ImageField(default='user_image/default.png', upload_to='user_image/')),
                ('status', models.CharField(choices=[('online', 'online'), ('offline', 'offline'), ('busy', 'busy'), ('away', 'away')], default='online', max_length=25)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UnreadMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unread_message', to='Chat.MessageChat')),
                ('remittance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unread_remittance', to='Remittance.Remittance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_unread', to='UserProfile.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20)),
                ('cvv_card', models.CharField(max_length=3)),
                ('month_card', models.CharField(max_length=2)),
                ('year_card', models.CharField(max_length=2)),
                ('phone_number', models.CharField(blank=True, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usercard', to='UserProfile.CustomUser')),
            ],
        ),
    ]
